# The reason we want to specify the distribution is that
# we want to install C libraries such as libvips
os: linux
dist: bionic

language: go

go:
  - 1.13.3

services:
  - docker

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

go_import_path: github.com/skygeario/skygear-server

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential pkg-config glib2.0-dev libexpat1-dev
  - curl -sfL https://github.com/libvips/libvips/releases/download/v8.8.3/vips-8.8.3a.tar.gz -o vips-8.8.3a.tar.gz
  - tar xzf vips-8.8.3a.tar.gz
  - "(cd vips-8.8.3 && ./configure && make && sudo make install)"
  - sudo ldconfig /usr/local

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1
  - make vendor

script:
  - make generate
  - git status | grep "_gen.go$"; test $? -eq 1
  - git status | grep "_string.go$"; test $? -eq 1
  - git status | grep "mockgen.*go$"; test $? -eq 1
  - make tidy
  - git status | grep "go.mod$"; test $? -eq 1
  - make lint
  - make test

deploy:
  - provider: releases
    api-key: "$GITHUB_RELEASE_TOKEN"
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      tags: true
      go: 1.13.3
  - provider: script
    script: ./scripts/deploy-docker-hub.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.13.3
  - provider: script
    script: ./scripts/deploy-quay-io.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.13.3
  - provider: script
    script: ./scripts/deploy-gh-pages.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      branch: next
      go: 1.13.3

notifications:
  slack:
    secure: "dza31bqJ4z51o2x4A0fowKxR6Brop/whekwIZ+JLfjBxZrIyYN0QxnHdi2kcEJwWFPtZdoenCRCLsCATB6/fkHieYkNrEpRjGkzVfOmtH7nYgC+870JH9gHGoWPkL1iTJ69Cl7cqBRXcR5Pr+wfl+RK+GdZnfKjyZTcr/dj1IS41sSCgGONhFmqMiwiJAlbvPIxOE4bbxJmnwHj71drWihLk7rweP0bqmq92/4fK0u/3to1Ng4X71ImSSqdbj+jyX9mNiMhkkPWdBupUOyMARcKo0B5jUwVy7GwlG68b8BoOkFwi4zNaQ44metHXt8EkMWGvaXYvSlnkzqDiT5ZlWBt5ZIruB4RmpGcMxTEAgM0LbJ5bm8Rp8D7K3NNTPNp6S/QS5bmpFIoRv8qXhbWaJ4qzmAOMQIIOzBRDXKWfaUNd5XHlvcIyyD7zLWJJRO4Sy+S5IjzBBRPJNW5XAB3MNt9FZt2DL/NK0u6uUEQsfoezuYq5BcWJ+1IJY/48UIL0z675jTHRiqAejrqorpneYHVPRRUh2fZf0HeW9tpheFFt1D77/dICvnvd7CWLdKaH7wRpicnKozegGGqthyTJs/iTAXbcIbYeBC1fA0/HOnSV7daPkrXcYHBuQqYOnfQae4KvkRc1tlQStEZz8qkMqaU4mBwihEjGky9wA19L/Mk="

env:
  global:
    - GO111MODULE=on
    # GITHUB_RELEASE_TOKEN
    - secure: "ZYxuSD05SgXD3oyzmOOw+o0QpQeG76yoOknP/bSh2uqGgf27qHy+gxvUqBXuJIKVZiKSlfSEO07XMGI5Jl9SqfqumFVdyh5jI2pKN+pZ5yuDokiJagb57jrM/CRaJj0df7qrBa21PGxXDQ52htv1GKGHSDifaXoOdAk9Uetp734RFBWsHXDNSN/RISuedVE5v5d05tB+CqqTAc3pjteDZhfFU5Z89yWaUtMBaGEW8++1Wd2kkMdrPm18dZ4Ylta/VVlxyDY8vtVJUOpXyeLTNAEMB/YsqP3Uauc46ynxbfqZLty4H+3pP24jgBuEQuxCeTcc8HDfi+5twVJtZ/1Xp+7GrD/6CjPnaLqafW6lDD06n62HOgI2/fxWWCKvQslKmpmxUQDDWtsQzS/YzncoN+RekHx1FZ8Nl+NRB5lSuUTtc96dUQD/lC5bl1mjMZS28G6yTtUodDnRBprjyI5vCzqQjE+gutzuMPGgom3NGqRRfNIXPmhyvhBpLbNdrxALSYf8F27PZ8dWxBUk95w/1HnfeEkTGZyWE1MkpKi9lKtsLHd4KTbqu6jRoVfPayJyj3FlddK6Lb0GM3OXuw9yb2kO60ZEvs4jLRzGAURnFVZCgUZgR+SfEB1Txn+X/0T1iFEzUKr3UpuU/c4onJLAf/xhkOsRr9BtsC5KE7pGz0M="
