language: go

go:
  - 1.8rc3
  - 1.7.5

matrix:
  allow_failures:
    - go: 1.8rc3

addons:
  postgresql: "9.5"

services:
  - redis-server
  - docker

cache:
  directories:
    - $HOME/.cache

go_import_path: github.com/skygeario/skygear-server

before_install:
  - mkdir -p $HOME/.cache/local
  - export LD_INSTALL_PREFIX=$HOME/.cache/local
  - export LD_LIBRARY_PATH=$LD_INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=$LD_INSTALL_PREFIX/lib:$LIBRARY_PATH
  - export PKG_CONFIG_PATH=$LD_INSTALL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
  - mkdir -p $LD_INSTALL_PREFIX/src
  - pushd $LD_INSTALL_PREFIX/src
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/jedisct1/libsodium.git 1.0.5
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/zeromq/zeromq4-1.git v4.1.3
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/zeromq/czmq.git v3.0.2
  - popd
  - go get github.com/Masterminds/glide

install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - glide install
  - go install

before_script:
  - psql -c 'CREATE DATABASE skygear_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d skygear_test
  - >
    go get golang.org/x/tools/cmd/stringer \
           golang.org/x/tools/cmd/cover \
           github.com/golang/lint/golint \
           github.com/rickmak/gocyclo \
           github.com/oursky/gogocyclo \
           github.com/mitchellh/gox

script:
  - WITH_ZMQ=1 make generate
  - git status | grep "_string.go$"; test $? -eq 1
  - WITH_ZMQ=1 make lint
  - WITH_ZMQ=1 make test

before_deploy:
  - if [[ ! -z "$TRAVIS_TAG" ]]; then make all archive; fi

deploy:
  - provider: releases
    api-key: "$GITHUB_RELEASE_TOKEN"
    file:
      - "dist/skygear-server-*.tar.gz"
      - "dist/skygear-server-*.zip"
    skip_cleanup: true
    file_glob: true
    on:
      repo: SkygearIO/skygear-server
      tags: true
      go: 1.7.5
  - provider: script
    script: ./scripts/deploy-docker-hub.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.7.5
  - provider: script
    script: ./scripts/deploy-quay-io.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.7.5

notifications:
  slack:
    secure: "dza31bqJ4z51o2x4A0fowKxR6Brop/whekwIZ+JLfjBxZrIyYN0QxnHdi2kcEJwWFPtZdoenCRCLsCATB6/fkHieYkNrEpRjGkzVfOmtH7nYgC+870JH9gHGoWPkL1iTJ69Cl7cqBRXcR5Pr+wfl+RK+GdZnfKjyZTcr/dj1IS41sSCgGONhFmqMiwiJAlbvPIxOE4bbxJmnwHj71drWihLk7rweP0bqmq92/4fK0u/3to1Ng4X71ImSSqdbj+jyX9mNiMhkkPWdBupUOyMARcKo0B5jUwVy7GwlG68b8BoOkFwi4zNaQ44metHXt8EkMWGvaXYvSlnkzqDiT5ZlWBt5ZIruB4RmpGcMxTEAgM0LbJ5bm8Rp8D7K3NNTPNp6S/QS5bmpFIoRv8qXhbWaJ4qzmAOMQIIOzBRDXKWfaUNd5XHlvcIyyD7zLWJJRO4Sy+S5IjzBBRPJNW5XAB3MNt9FZt2DL/NK0u6uUEQsfoezuYq5BcWJ+1IJY/48UIL0z675jTHRiqAejrqorpneYHVPRRUh2fZf0HeW9tpheFFt1D77/dICvnvd7CWLdKaH7wRpicnKozegGGqthyTJs/iTAXbcIbYeBC1fA0/HOnSV7daPkrXcYHBuQqYOnfQae4KvkRc1tlQStEZz8qkMqaU4mBwihEjGky9wA19L/Mk="

env:
  global:
    # GITHUB_RELEASE_TOKEN
    - secure: hR1f2OUGObjC8h+ks5N6QNxoaCDROYBPOGqDI5USVC4/9eBoFbPGDmVddRj1KM6Uz6UCSTQfmyQHJD8uP8k86Bme/LDyca52oRNQ/F5IqzkiyJR4i46Cmi5OIe9ba9nGRjpBc47/7EK4JMnqJ1WZkzxyDtSFzx7ImxMaHWLgMaZevgmWpPedDImQgg9z4KeNE6K/sR14DHk/B9tBtxd8yN6avBRwTrzgLAfrXY4KiocbD8JHQNe+HaPPEhy9oeT1VdDjOZfYtJtJfl9wIoIb3KFuRwIjWLiCmuKyOuxZLB0dBQtFmc9YzIgASSytJ/WLN41x6ZuQzawkG0Ds+x53sa+FW7nVDkGP1DluuVwkTQS0IvJR/QnFTkyiQjIX+H24HWuCnMvuxTOS5B5gvSHKmUP0iBqFSbB/CaZZL69XPr3DcEPRwSsLqHJGQreyK+BMAcnD8zk2J1TK4j89FxEbvyXrStDHy0TflmHwMej63qw8Imtr6bDYlp+1stFl4wlT9JuMPbrtLye4vP6hP/lhmj1WwmIZn5Vyvej5BWTwnon+S8Hm+0Mm7QXOg5+gamo5WRPyHIhT614rjmnaKd2DA13Apn+tHsHa/3uapZRpF/mzEJlsx8ug2b3dsWSzOU3+x03HmiKVE2OJlQwIWppeYZFrK/pyrfPWoSRLQyUnYa4=
