language: go

sudo: false

go:
  - 1.5
  - 1.6

addons:
  postgresql: "9.4"

services:
  - redis-server

cache:
  directories:
    - $HOME/.cache
    - Godeps/_workspace

go_import_path: github.com/skygeario/skygear-server

before_install:
  - mkdir -p $HOME/.cache/local
  - export LD_INSTALL_PREFIX=$HOME/.cache/local
  - export LD_LIBRARY_PATH=$LD_INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=$LD_INSTALL_PREFIX/lib:$LIBRARY_PATH
  - export PKG_CONFIG_PATH=$LD_INSTALL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
  - mkdir -p $LD_INSTALL_PREFIX/src
  - pushd $LD_INSTALL_PREFIX/src
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/jedisct1/libsodium.git 1.0.5
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/zeromq/zeromq4-1.git v4.1.3
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/zeromq/czmq.git v3.0.2
  - popd
  - ./scripts/if-differ.sh Godeps/Godeps.json $HOME/.cache/Godeps.json rm -rf Godeps/_workspace

before_script:
  - psql -c 'CREATE DATABASE skygear_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d skygear_test
  - >
    go get golang.org/x/tools/cmd/stringer \
           golang.org/x/tools/cmd/cover \
           github.com/golang/lint/golint \
           github.com/smartystreets/goconvey/convey \
           github.com/smartystreets/assertions \
           github.com/rickmak/gocyclo \
           github.com/oursky/gogocyclo \
           github.com/jarcoal/httpmock

script:
  - golint ./... | grep -v -f .golint.exclude; test $? -eq 1
  - go generate ./...
  - git status | grep "_string.go$"; test $? -eq 1
  - gocyclo -skip-godeps -over 15 . | gogocyclo
  - go test --tags zmq -cover ./...

before_deploy:
  - ./scripts/build-binary.sh

deploy:
  - provider: releases
    api-key: "$GITHUB_RELEASE_TOKEN"
    file:
      - "dist/skygear-server-darwin-386"
      - "dist/skygear-server-darwin-amd64"
      - "dist/skygear-server-linux-386"
      - "dist/skygear-server-linux-amd64"
      - "dist/skygear-server-windows-386"
      - "dist/skygear-server-windows-amd64"
      - "dist/skygear-server-zmq-linux-amd64"
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      go: 1.5
      tags: true
  - provider: script
    script: ./scripts/upload-binary.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.5
  - provider: script
    script: ./scripts/trigger-docker-hub.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.5
  - provider: script
    script: ./scripts/trigger-quay-io.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.5

notifications:
  slack:
    secure: "dza31bqJ4z51o2x4A0fowKxR6Brop/whekwIZ+JLfjBxZrIyYN0QxnHdi2kcEJwWFPtZdoenCRCLsCATB6/fkHieYkNrEpRjGkzVfOmtH7nYgC+870JH9gHGoWPkL1iTJ69Cl7cqBRXcR5Pr+wfl+RK+GdZnfKjyZTcr/dj1IS41sSCgGONhFmqMiwiJAlbvPIxOE4bbxJmnwHj71drWihLk7rweP0bqmq92/4fK0u/3to1Ng4X71ImSSqdbj+jyX9mNiMhkkPWdBupUOyMARcKo0B5jUwVy7GwlG68b8BoOkFwi4zNaQ44metHXt8EkMWGvaXYvSlnkzqDiT5ZlWBt5ZIruB4RmpGcMxTEAgM0LbJ5bm8Rp8D7K3NNTPNp6S/QS5bmpFIoRv8qXhbWaJ4qzmAOMQIIOzBRDXKWfaUNd5XHlvcIyyD7zLWJJRO4Sy+S5IjzBBRPJNW5XAB3MNt9FZt2DL/NK0u6uUEQsfoezuYq5BcWJ+1IJY/48UIL0z675jTHRiqAejrqorpneYHVPRRUh2fZf0HeW9tpheFFt1D77/dICvnvd7CWLdKaH7wRpicnKozegGGqthyTJs/iTAXbcIbYeBC1fA0/HOnSV7daPkrXcYHBuQqYOnfQae4KvkRc1tlQStEZz8qkMqaU4mBwihEjGky9wA19L/Mk="

env:
  global:
    # BINTRAY_API_KEY
    - secure: ozy/O7WQjCUqRDZvsVRPHibl3sq8Vw6ZbGLy3NmH0CdxK5NR1i8ybJOsYsPjS8aTQ7TWvL63oxD0zusf8a1omdaSXGjSyoOlqR+/0L3qtfWHxbvYGgRnaGuQ0Aoj1CzRyxyl22+vCsXPMubsh3/MDNHYhkhFykTWSG+So+G8UNCS6kFF/EOmWJtE/d5GzNQ6AwjwcR0gpU/KL+iXkdZENqBGbdPf3eVwp6ZVPC51hAKpXQ0c42Gkrhgaum7XZMuXXb6xPVihOj564df8qCJF9gajNQPyn9gSONl42RPZzKDFM6wxUOTzj3RFq26Ou5OQCyhV6Dir9HClmA5AT009wh50R+oMdevPfmIzAX/eIq5gaVTmR9K2z78tkEXS4DEI8J3DMRr6eYMFPoKRP8CYrnoL0XhfBdcBoHFxcA2xWlvU65gcxoZTWhi0AQM2TuztTUW2L161qytqf72mBZhZW8GhkHZLN0UNqzwDTIq0o+yK1wV1NXz6vo1KP+9L6VkhXQKzuzd+tKIEoZIvxg1rDcU9rCpSXhMFYM9QNs4igu2JTmm8VMU3yGxIWtx9iSSzTJHdGdMxe38C8QBWI+AFgdc7skTQsv6H9cpTxpDiycPr+6U4L1Tk3o5QnVH5qxNrH+xJXsAuZ4DG/7qGgkp8o84ygf4/feWc5zll7zAtiOg=
    # GITHUB_RELEASE_TOKEN
    - secure: hR1f2OUGObjC8h+ks5N6QNxoaCDROYBPOGqDI5USVC4/9eBoFbPGDmVddRj1KM6Uz6UCSTQfmyQHJD8uP8k86Bme/LDyca52oRNQ/F5IqzkiyJR4i46Cmi5OIe9ba9nGRjpBc47/7EK4JMnqJ1WZkzxyDtSFzx7ImxMaHWLgMaZevgmWpPedDImQgg9z4KeNE6K/sR14DHk/B9tBtxd8yN6avBRwTrzgLAfrXY4KiocbD8JHQNe+HaPPEhy9oeT1VdDjOZfYtJtJfl9wIoIb3KFuRwIjWLiCmuKyOuxZLB0dBQtFmc9YzIgASSytJ/WLN41x6ZuQzawkG0Ds+x53sa+FW7nVDkGP1DluuVwkTQS0IvJR/QnFTkyiQjIX+H24HWuCnMvuxTOS5B5gvSHKmUP0iBqFSbB/CaZZL69XPr3DcEPRwSsLqHJGQreyK+BMAcnD8zk2J1TK4j89FxEbvyXrStDHy0TflmHwMej63qw8Imtr6bDYlp+1stFl4wlT9JuMPbrtLye4vP6hP/lhmj1WwmIZn5Vyvej5BWTwnon+S8Hm+0Mm7QXOg5+gamo5WRPyHIhT614rjmnaKd2DA13Apn+tHsHa/3uapZRpF/mzEJlsx8ug2b3dsWSzOU3+x03HmiKVE2OJlQwIWppeYZFrK/pyrfPWoSRLQyUnYa4=
    # DOCKER_HUB_TRIGGER_TOKEN
    - secure: "mIPp1kxXCQaNeSy/7vXpI03JXmI4bDpN4/0KZzmTl2DhuwZM1oa5tNJmJrcnckHzeygGTjVyEu77f9NGbZNI9FqsARfKFVepEFQi1ATEO6FCXpDlisWMktp6zoFToh4FWJi0q9Hkuu0MfSXT/7BXWFKMmTtMTWeVCXenQsATjpO+TwOp6DNS0nEORiQ+GLIHYd4SeLMZfS0sKvGirGIrDkloOIjlhgRgJ6+2mew9Ho65hnWa46MUtzLeq4QkTLH+Y66dLAnt1thQYcH1fSgUdAZjgnpIJIHgbFFscE+eXqQpAe4SulDMtY/gkEDmGnqRIEl1LREUVMDSWPe+Y7BTkEojej5rWKkDbihLPK4dC+s5bHQxmDw/FiKy3P7nAz3LigF/FkFwGtzgCt3WaI09igUL5h8sbc1Wd0kpDPDfCRemkU2AK233nRqThTGnyF+3m8kBtqUFB1fA0ZDf+g1SRi/qJOxDCyymBBFZ2gBAHSwfJqYugjbTxT0hyCvHzYQCD+MfEJXnx13SfiQVRIfTVE5x+8JDm9kdviuPbEVKdv9pn8ynmCicrpBxlzXiHpKiI/WCR79AxAWn3bjmNbJKijYZrUpc4P4Apm4Wv8xTD2umquRCWctHW/pbZCwJdN8tCYAvTDjZU0LmPmMtlFx5ANxl14ld1+GEfxRAtXjtvgI="
    # QUAY_IO_ACCESS_TOKEN
    - secure: "kxpaBYrIiN/LhCocsseXB9XlPYNNEpwydpf/cnb49tY5qnS3TIceTbxNU2ACfrI0ePRaXB1JqSak8EzCBBvHklmH9RJTJVHrFfzZBLit1GxGa1KBoBQZT+xM63WYHPuIFmj2KcFJnO287szLpve6+AOq5sn57b6Qn8NC4/COw68jdQRnCDbsz8zl6nOOuBJi5Y72daksfTvdtovW1UZ2hr3IJtLckv1Up+lINAiLnNYbjD2SmsiqGFHHWEtmqLsCFNindHNmXHhrb3HkNWtUwPJKMx2l0ZqS2UoBQmirY7CWm1vu5QRkMnaxU9X25VD/3hndogdcl0FhudejcmIwo0QXLtVZwJR90yA9XMca/7+4T1l/sTcf0Xr9WFbGbyDgB2mQWgYtLCi4dOvmicVi1oc1dM6ni0E/91Vk4JwQu8CjsaofzF5/zx8hOXOH2zXj8uLBkNXkI4S8/jFum9pekBTSW2mtQ0iKvCI4FNgHM/62ZXGrT23Aquo4go1176xwMYufQ7+GxoQy2Mp9NMqNHdJ1IbgL5V7drcoS2msiyTNqfT7es6lEEJt7Cmfxiy9/PDCzU7E78V5nLGl4oda8kmqSVxE+5SlLUAOp2yvgAfdiDqgy+/8CKAlATYnDEe9/cNq3eqE2k4zJhFL5GLTuQ0U+wi69NmURyCcOa56N6WM="
